import { GoogleGenAI } from "@google/genai";
import { AnalysisMode, AnalysisResult } from '../types';

const getClient = () => new GoogleGenAI({ apiKey: process.env.API_KEY });

const SYSTEM_PROMPT = `
You are an elite Windows Kernel and Registry Forensics Engineer. You interpret raw binary data from Windows Registry Hives (NTUSER.DAT, SYSTEM, SAM, SOFTWARE).

You are an expert in the following structures:
- **Base Block (regf)**: The file header.
- **Hive Bins (hbin)**: The memory allocation units.
- **Key Nodes (nk)**: Defines registry keys. Crucial offsets: 0x02 (Flags), 0x14 (Parent), 0x2C (Key Name).
- **Value Keys (vk)**: Defines values.
- **Security Keys (sk)**: Defines ACLs and SIDs.
- **Cell Indexes**: The logic pointers within the hive.

Your job is to solve specific obfuscation and corruption problems provided by the user. 
Always output valid JSON.
IMPORTANT: You must strictly escape backslashes in Windows paths. For example, use "C:\\\\Windows" instead of "C:\\Windows".
`;

export const analyzeHiveChunk = async (
  hexString: string, 
  mode: AnalysisMode, 
  offset: number
): Promise<AnalysisResult> => {
  const ai = getClient();
  
  let problemStatement = "";
  
  switch (mode) {
    case AnalysisMode.GHOST_VIRTUALIZATION:
      problemStatement = `
        PROBLEM: Detect "Fully Virtualized Keys" or "Ghost Keys" that do not exist in the physical file but are dynamically presented by the kernel.
        TASK: Analyze the 'nk' (Key Node) flags at relative offset 0x02.
        - Look for Flag 0x10 (Hive Entry Point) or 0x20 (Symbolic Link).
        - Look for high volatility indicators.
        - If a Key Name suggests a container (e.g., unrelated to surrounding keys), identify it.
      `;
      break;
    case AnalysisMode.ACL_CLOAKING:
      problemStatement = `
        PROBLEM: Detect "Hidden System Keys" hidden via aggressive ACLs.
        TASK: Analyze the 'sk' (Security Key) cell structure.
        - Look for a Security Descriptor where the DACL (Discretionary Access Control List) is NULL or Empty (allowing no access).
        - Look for DENY ACEs targeting SYSTEM (S-1-5-18) or Administrators (S-1-5-32-544).
        - Check if the 'sk' reference in the 'nk' node points to a valid descriptor.
      `;
      break;
    case AnalysisMode.PERMISSION_BYPASS:
      problemStatement = `
        PROBLEM: User has "Access Denied" on this key.
        TASK: Analyze the ownership and inheritance flags.
        - Identify the Owner SID in the security descriptor.
        - Determine if the 'WriteDacl' right is missing from the current user's effective rights.
        - Suggest a raw hex edit to replace the 'sk' pointer with a known permissive security cell index.
      `;
      break;
    case AnalysisMode.COMPOSITE_LAYERING:
      problemStatement = `
        PROBLEM: This is a "Composite Key" generated by the Windows Virtualization Layer (merging User vs System hives).
        TASK: Look for inconsistencies in the key structure.
        - Analyze the 'Timestamp' field (offset 0x04 in 'nk'). 
        - If the parent key implies it is older than the virtualization root, or if the structure implies a 'Merge' operation (presence of class names related to virtualization).
      `;
      break;
    case AnalysisMode.INTEGRITY_RECOVERY:
      problemStatement = `
        PROBLEM: Key contains "Illegal Characters" (Null bytes) or is Corrupted.
        TASK: Recover the true key name and structure.
        - Scan the Key Name field. Are there 0x00 bytes *before* the defined length ends? (This breaks standard APIs).
        - Check for non-ASCII or malformed UTF-16LE characters.
        - specific focus: Pointer loops or cell lengths that exceed the bin size.
      `;
      break;
  }

  const fullPrompt = `
    ${problemStatement}
    
    INPUT CONTEXT:
    - Base Offset: 0x${offset.toString(16)}
    - Hex Data (Space Separated): ${hexString}

    RETURN JSON format:
    {
      "title": "Short Technical Finding",
      "description": "Explanation of the anomaly found.",
      "severity": "low" | "medium" | "high" | "critical",
      "technicalDetails": "Specific byte offsets (e.g. 'Byte at 0x02 is 0x20').",
      "recommendation": "How to fix or interpret (e.g. 'Patch offset 0x2C to remove null byte').",
      "offsetDetected": "0x..."
    }
  `;

  try {
    const response = await ai.models.generateContent({
      model: 'gemini-2.5-flash',
      contents: fullPrompt,
      config: {
        responseMimeType: "application/json",
        systemInstruction: SYSTEM_PROMPT
      }
    });

    let text = response.text;
    if (!text) throw new Error("No response from AI");
    
    // Cleanup: Remove Markdown code blocks if present
    text = text.replace(/^```json\s*/g, "").replace(/\s*```$/g, "").trim();

    try {
      return JSON.parse(text) as AnalysisResult;
    } catch (e) {
      console.warn("First JSON parse attempt failed. Trying to fix bad escapes...", e);
      // Heuristic Fix: Double-escape backslashes that are NOT valid escape sequences
      // This looks for a backslash followed by a char that isn't ", \, /, b, f, n, r, t, u
      const fixedText = text.replace(/\\(?![/\\bfnrtu"])/g, "\\\\");
      try {
         return JSON.parse(fixedText) as AnalysisResult;
      } catch (e2) {
         console.error("Gemini JSON Parsing Failed. Raw text:", text);
         return {
            title: "Analysis Parsing Error",
            description: "The AI model returned invalid JSON data that could not be repaired.",
            severity: "low",
            technicalDetails: `JSON Error: ${(e2 as Error).message}. Raw Output snippet: ${text.substring(0, 50)}...`,
            recommendation: "Try selecting a smaller chunk of data or a valid record boundary."
         };
      }
    }
  } catch (error) {
    console.error("Gemini Analysis Network Error:", error);
    return {
      title: "Analysis Failed",
      description: "The AI model could not process this binary chunk.",
      severity: "low",
      technicalDetails: String(error),
      recommendation: "Check your network connection or API key."
    };
  }
};